"""Edge-case regex corpus for libfte regression testing.

Each entry pins a regex + a length spec (fixed ``length`` or a
``(min_length, max_length)`` range) chosen so the format is non-empty.
The frozen expected values live in ``regex_corpus_golden.json``; regenerate that
file with ``gen_regex_corpus_golden.py`` ONLY when a ranking change is intentional
(it changes the wire format and both endpoints must agree).

The corpus spans both regex-feature edge cases and a wide range of DFA
shapes: state counts from a handful up to a few thousand, transition counts
up to several thousand, and alphabets from 2 to 256 symbols (the ``dfa_*``
entries), so the general ranking walk is exercised, not just flat languages.

regex2dfa quirks the patterns respect: no ``{n}``/``{n,m}`` quantifiers
(braces are literal), no ``\\x`` escapes; ``.`` means any of 256 bytes.
"""

from __future__ import annotations

# (id, pattern, length_spec, tags): length_spec is an int (fixed length=)
# or a (min_length, max_length) tuple.
CORPUS: list[tuple[str, str, object, list[str]]] = [
    ('pow2_b2_binary', '^[01]+$', 64, ['flat', 'pow2', 'b2']),
    ('pow2_b4', '^[0-3]+$', 40, ['flat', 'pow2', 'b4']),
    ('pow2_b8_octal', '^[0-7]+$', 32, ['flat', 'pow2', 'b8']),
    ('pow2_b16_hex', '^[0-9a-f]+$', 32, ['flat', 'pow2', 'b16']),
    ('pow2_b32', '^[0-9a-v]+$', 24, ['flat', 'pow2', 'b32']),
    ('pow2_b64_base64', '^[0-9A-Za-z+/]+$', 20, ['flat', 'pow2', 'b64']),
    ('pow2_b256_dot', '^.+$', 16, ['flat', 'pow2', 'b256', 'dot']),
    ('flat_b3', '^[a-c]+$', 20, ['flat', 'b3']),
    ('flat_b5_vowels', '^[aeiou]+$', 20, ['flat', 'b5', 'gap']),
    ('flat_b6_gap', '^[a-cx-z]+$', 20, ['flat', 'b6', 'gap']),
    ('flat_b7', '^[a-g]+$', 18, ['flat', 'b7']),
    ('flat_b9', '^[a-i]+$', 16, ['flat', 'b9']),
    ('flat_b10_digits', '^[0-9]+$', 24, ['flat', 'b10']),
    ('flat_b25', '^[a-y]+$', 16, ['flat', 'b25']),
    ('flat_b26_lower', '^[a-z]+$', 32, ['flat', 'b26']),
    ('flat_b26_upper', '^[A-Z]+$', 16, ['flat', 'b26']),
    ('flat_b36', '^[0-9a-z]+$', 16, ['flat', 'b36']),
    ('flat_b52_letters', '^[A-Za-z]+$', 16, ['flat', 'b52']),
    ('flat_b62_alnum', '^[A-Za-z0-9]+$', 16, ['flat', 'b62']),
    ('flat_b95_print', '^[ -~]+$', 12, ['flat', 'b95', 'printable']),
    ('union_singles', '^(a|b|c)+$', 12, ['union']),
    ('union_words_eq', '^(cat|dog|bat)+$', 9, ['union', 'multichar']),
    ('union_difflen', '^(a|bb|ccc)+$', 6, ['union', 'skew', 'varlen']),
    ('union_overlap', '^(0|1|00|11)+$', 6, ['union', 'overlap']),
    ('union_pairs', '^(ab|cd|ef)+$', 8, ['union', 'multichar']),
    ('union_shared_prefix', '^(abc|abd|abe)+$', 6, ['union', 'min-edge']),
    ('union_ab', '^(a|b)+$', 20, ['union', 'b2-like']),
    ('union_nested', '^((a|b)|(c|d))+$', 10, ['union', 'nested']),
    ('url_path_html', '^/[a-z]+/[a-z]+\\.html$', 24, ['concat', 'literal', 'protocol']),
    ('http_req_line', '^GET /[a-z]+ HTTP/1\\.1$', 22, ['concat', 'literal', 'protocol', 'space']),
    ('email_ish', '^[a-z]+@[a-z]+\\.com$', 18, ['concat', 'literal', 'protocol']),
    ('cookie_ish', '^user=[a-z]+;id=[0-9]+$', 20, ['concat', 'literal', 'protocol']),
    ('prefix_var', '^PREFIX[a-z]+$', 14, ['concat', 'literal', 'prefix']),
    ('var_suffix', '^[a-z]+SUFFIX$', 14, ['concat', 'literal', 'suffix']),
    ('version_str', '^v[0-9]+\\.[0-9]+$', 8, ['concat', 'literal']),
    ('domain_3label', '^[a-z]+\\.[a-z]+\\.[a-z]+$', 21, ['concat', 'literal', 'protocol']),
    ('ipv4_ish', '^[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+$', 15, ['concat', 'literal', 'protocol']),
    ('kv_query', '^[a-z]+=[a-z]+&[a-z]+=[a-z]+$', 24, ['concat', 'literal', 'protocol']),
    ('filename', '^[a-z]+\\.[a-z]+$', 12, ['concat', 'literal']),
    ('opt_mid', '^ab?c$', (2, 3), ['optional']),
    ('opt_colour', '^colou?r$', (5, 6), ['optional']),
    ('opt_group', '^(abc)?xyz$', (3, 6), ['optional', 'group']),
    ('opt_scheme', '^https?://[a-z]+$', (11, 12), ['optional', 'protocol']),
    ('periodic_2', '^(ab)+$', 12, ['periodic', 'even']),
    ('periodic_3', '^(abc)+$', 12, ['periodic', 'mult3']),
    ('star_then_lit', '^(a|b)*c$', 11, ['star', 'concat']),
    ('group_plus', '^((a|b)c)+$', 12, ['periodic']),
    ('nested_plus', '^(a+b+)+$', 10, ['nested', 'plus']),
    ('alt_letter_digit', '^([a-z][0-9])+$', 12, ['periodic', 'alternating']),
    ('parity_aa', '^(aa)+$', 10, ['parity', 'even']),
    ('loop_mixed_len', '^(a|bb)+$', 8, ['loop', 'varlen', 'skew']),
    ('nonuniform_abc', '^a(b|c)+$', 8, ['nonuniform', 'deadpath']),
    ('nonuniform_abba', '^ab+a$', (3, 8), ['nonuniform', 'deadpath']),
    ('nonuniform_ac', '^[ac]+$', 16, ['nonuniform']),
    ('nonuniform_x_yy', '^(x|yy)+$', 8, ['nonuniform', 'skew', 'varlen']),
    ('nonuniform_prefixed', '^(a|ab|abc)+$', 9, ['nonuniform', 'skew', 'shared-prefix']),
    ('base64_padded', '^[A-Za-z0-9+/]+==$', 16, ['protocol', 'base64', 'concat']),
    ('uuid_hexgroups', '^[0-9a-f]+-[0-9a-f]+$', 17, ['protocol', 'hex', 'concat']),
    ('path_multi', '^(/[a-z]+)+$', 16, ['protocol', 'periodic']),
    ('hostport', '^[a-z]+:[0-9]+$', 12, ['protocol', 'concat']),
    ('dot_hostname', '^[a-z]+(\\.[a-z]+)+$', 16, ['protocol', 'concat', 'periodic']),
    ('mac_ish', '^([0-9a-f][0-9a-f]:)+[0-9a-f][0-9a-f]$', 17, ['protocol', 'hex']),
    ('finite_literal', '^hello$', 5, ['finite', 'card1']),
    ('finite_two', '^(a|b)$', 1, ['finite', 'len1']),
    ('finite_catdog', '^(cat|dog)$', 3, ['finite', 'card2']),
    ('finite_pair', '^(ab|cd)$', 2, ['finite']),
    ('space_two_words', '^[a-z]+ [a-z]+$', 12, ['space', 'concat']),
    ('words_spaced', '^([a-z]+ )+[a-z]+$', 20, ['space', 'periodic']),
    ('class_comma', '^[a-z,]+$', 12, ['punct', 'class']),
    ('class_dot', '^[a-z.]+$', 12, ['punct', 'class']),
    ('class_punct', '^[!@#%^&*]+$', 10, ['punct', 'class']),
    ('tab_sep', '^[a-z]+\\t[a-z]+$', (7, 12), ['whitespace', 'concat']),
    ('mixed_upper_lower', '^[a-zA-Z]+$', 16, ['mixed']),
    ('class_alnum_space', '^[a-zA-Z0-9 ]+$', 14, ['mixed', 'space']),
    ('class_word_punct', '^[a-z!?.]+$', 12, ['mixed', 'punct']),
    ('len_sweep_1', '^[a-z]+$', 1, ['len-edge', 'len1']),
    ('len_sweep_2', '^[a-z]+$', 2, ['len-edge']),
    ('len_sweep_8', '^[a-z]+$', 8, ['len-edge']),
    ('len_sweep_64', '^[a-z]+$', 64, ['len-edge']),
    ('len_sweep_256', '^[a-z]+$', 256, ['len-edge', 'large']),
    ('len_sweep_1024', '^[a-z]+$', 1024, ['len-edge', 'large']),
    ('hex_large_512', '^[0-9a-f]+$', 512, ['flat', 'pow2', 'large']),
    ('binary_large_1024', '^[01]+$', 1024, ['flat', 'pow2', 'large']),
    ('var_lower_4_8', '^[a-z]+$', (4, 8), ['varlen', 'range']),
    ('var_hex_8_16', '^[0-9a-f]+$', (8, 16), ['varlen', 'range', 'pow2']),
    ('var_words_3_12', '^(cat|dog|bird)+$', (3, 12), ['varlen', 'range', 'union']),
    ('var_alnum_10_20', '^[A-Za-z0-9]+$', (10, 20), ['varlen', 'range']),
    ('var_binary_1_32', '^[01]+$', (1, 32), ['varlen', 'range', 'pow2']),
    ('var_digits_1_1', '^[0-9]+$', (1, 1), ['varlen', 'degenerate']),
    ('skew_1234', '^(a|bb|ccc|dddd)+$', 8, ['skew', 'nonuniform']),
    ('skew_geom', '^(a|ba|bba|bbba)+$', 8, ['skew', 'nonuniform']),
    ('skew_longtail', '^(a|aaaab)+$', (5, 10), ['skew', 'varlen']),
    ('dot_middle', '^[a-z].[a-z]$', 3, ['dot', 'wildcard']),
    ('dot_plus_short', '^.+$', 4, ['dot', 'b256']),
    ('explicit_3', '^[a-z][a-z][a-z]$', 3, ['explicit', 'fixed']),
    ('explicit_mixed', '^[a-z][0-9][a-z]$', 3, ['explicit', 'fixed']),
    ('union_empty_branch', '^(a|)b$', (1, 2), ['optional-alt', 'edge']),
    ('deep_nest', '^((ab)|(cd)|(ef))+$', 8, ['union', 'nested']),
    ('alt_star', '^(a*b)+$', 8, ['star', 'nested', 'skew']),
    ('plus_of_opt', '^(ab?)+$', 8, ['optional', 'loop', 'skew']),

    # --- DFA-complexity coverage: a wide range of states, transitions,
    # and alphabet sizes (states ~4..4097, transitions ~8..8192, |sigma|
    # 2..256). These stress the general Goldberg-Sipser walk, the path
    # that the flat single-alphabet fast paths cannot shortcut. ---
    ('dfa_pfe_end4_bin', '^[01]*1[01][01][01]$', 20, ['dfa', 'manystates', 'positional', 'b2']),
    ('dfa_pfe_end6_bin', '^[01]*1[01][01][01][01][01]$', 24, ['dfa', 'manystates', 'positional', 'b2']),
    ('dfa_pfe_end8_bin', '^[01]*1[01][01][01][01][01][01][01]$', 28, ['dfa', 'manystates', 'positional', 'b2']),
    ('dfa_pfe_end9_bin', '^[01]*1[01][01][01][01][01][01][01][01]$', 28, ['dfa', 'manystates', 'positional', 'b2']),
    ('dfa_pfe_end10_bin', '^[01]*1[01][01][01][01][01][01][01][01][01]$', 28, ['dfa', 'manystates', 'positional', 'b2']),
    ('dfa_pfe_end12_bin', '^[01]*1[01][01][01][01][01][01][01][01][01][01][01]$', 30, ['dfa', 'manystates', 'positional', 'b2', 'extreme']),
    ('dfa_pfe_end3_az', '^[a-z]*a[a-z][a-z]$', 12, ['dfa', 'manystates', 'manytransitions', 'positional', 'b26']),
    ('dfa_pfe_end5_az', '^[a-z]*a[a-z][a-z][a-z][a-z]$', 12, ['dfa', 'manystates', 'manytransitions', 'positional', 'b26']),
    ('dfa_pfe_end7_az', '^[a-z]*a[a-z][a-z][a-z][a-z][a-z][a-z]$', 14, ['dfa', 'manystates', 'manytransitions', 'positional', 'b26']),
    ('dfa_pfe_end4_b4', '^[0-3]*0[0-3][0-3][0-3]$', 12, ['dfa', 'manystates', 'positional', 'b4']),
    ('dfa_dot_ends2', '^.*ab$', 8, ['dfa', 'manytransitions', 'contains', 'b256']),
    ('dfa_dot_ends4', '^.*abcd$', 16, ['dfa', 'manytransitions', 'contains', 'b256']),
    ('dfa_dot_ends8', '^.*abcdefgh$', 20, ['dfa', 'manytransitions', 'contains', 'b256']),
    ('dfa_dot_contains8', '^.*abcdefgh.*$', 16, ['dfa', 'manytransitions', 'contains', 'b256']),
    ('dfa_dot_mixed', '^.[a-z].[a-z].[a-z].$', 7, ['dfa', 'manytransitions', 'b256']),
    ('dfa_print_contains', '^[ -~]*token[ -~]*$', 14, ['dfa', 'manytransitions', 'contains', 'b95']),
    ('dfa_lit8', '^abcdefgh$', 8, ['dfa', 'manystates', 'literal', 'finite']),
    ('dfa_lit16', '^abcdefghijklmnop$', 16, ['dfa', 'manystates', 'literal', 'finite']),
    ('dfa_lit24', '^abcdefghijklmnopqrstuvwx$', 24, ['dfa', 'manystates', 'literal', 'finite']),
    ('dfa_lit32', '^abcdefghijklmnopqrstuvwxyzABCDEF$', 32, ['dfa', 'manystates', 'literal', 'finite']),
    ('dfa_lit48', '^abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv$', 48, ['dfa', 'manystates', 'literal', 'finite']),
    ('dfa_nato5', '^(alpha|bravo|charlie|delta|echo)$', (3, 7), ['dfa', 'manystates', 'trie', 'union']),
    ('dfa_nato10', '^(alpha|bravo|charlie|delta|echo|foxtrot|golf|hotel|india|juliet)$', (3, 7), ['dfa', 'manystates', 'trie', 'union']),
    ('dfa_nato26', '^(alpha|bravo|charlie|delta|echo|foxtrot|golf|hotel|india|juliet|kilo|lima|mike|november|oscar|papa|quebec|romeo|sierra|tango|uniform|victor|whiskey|xray|yankee|zulu)$', (2, 8), ['dfa', 'manystates', 'trie', 'union']),
    ('dfa_months', '^(january|february|march|april|may|june|july|august|september|october|november|december)$', (3, 9), ['dfa', 'manystates', 'trie', 'union']),
    ('dfa_keywords', '^(if|else|elif|while|for|return|break|continue|def|class|import|from|pass|raise|yield|lambda|with|try|except|finally|global|assert)$', (2, 8), ['dfa', 'manystates', 'trie', 'union']),
    ('dfa_contains3', '^[a-z]*abc[a-z]*$', 12, ['dfa', 'contains', 'b26']),
    ('dfa_contains5', '^[a-z]*abcde[a-z]*$', 12, ['dfa', 'contains', 'b26']),
    ('dfa_contains8', '^[a-z]*abcdefgh[a-z]*$', 16, ['dfa', 'contains', 'b26']),
    ('dfa_contains12', '^[a-z]*abcdefghijkl[a-z]*$', 20, ['dfa', 'contains', 'b26']),
    ('dfa_contains16', '^[a-z]*abcdefghijklmnop[a-z]*$', 24, ['dfa', 'contains', 'b26']),
    ('dfa_ipv4', '^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])\\.(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9][0-9]|[0-9])$', (7, 15), ['dfa', 'protocol', 'numberrange']),
    ('dfa_time_hms', '^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$', 8, ['dfa', 'protocol', 'numberrange']),
    ('dfa_date_iso', '^(19|20)[0-9][0-9]-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$', 10, ['dfa', 'protocol', 'numberrange']),
    ('dfa_csv5', '^[a-z]+,[a-z]+,[a-z]+,[a-z]+,[a-z]+$', (9, 20), ['dfa', 'protocol', 'concat']),
    ('dfa_mac', '^[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]$', 17, ['dfa', 'protocol', 'hex']),
    ('dfa_uuid5', '^[0-9a-f]+-[0-9a-f]+-[0-9a-f]+-[0-9a-f]+-[0-9a-f]+$', (9, 24), ['dfa', 'protocol', 'hex', 'concat']),
    ('dfa_semver', '^[0-9]+\\.[0-9]+\\.[0-9]+$', (5, 14), ['dfa', 'protocol', 'numberrange']),
    ('dfa_hostname4', '^[a-z]+\\.[a-z]+\\.[a-z]+\\.[a-z]+$', (7, 20), ['dfa', 'protocol', 'concat']),
    ('dfa_hexcolor', '^#[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]$', 7, ['dfa', 'protocol', 'hex']),
    ('dfa_percentage', '^(100|[1-9][0-9]|[0-9])%$', (2, 4), ['dfa', 'protocol', 'numberrange', 'varlen']),
    ('dfa_phone_us', '^[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]$', 12, ['dfa', 'protocol', 'concat']),
    ('dfa_http_verb', '^(GET|POST|PUT|DELETE|HEAD|PATCH) /[a-z]+$', (6, 16), ['dfa', 'protocol', 'union', 'varlen']),
    ('dfa_urlquery', '^/[a-z]+\\?[a-z]+=[a-z]+&[a-z]+=[a-z]+$', (13, 28), ['dfa', 'protocol', 'concat', 'varlen']),
    ('dfa_mod3_bin', '^([01][01][01])+$', 18, ['dfa', 'periodic', 'b2']),
    ('dfa_mod5_dig', '^([0-9][0-9][0-9][0-9][0-9])+$', 20, ['dfa', 'periodic', 'b10']),
    ('dfa_mod7_bin', '^([01][01][01][01][01][01][01])+$', 21, ['dfa', 'periodic', 'b2']),
    ('dfa_mod4_az', '^([a-z][a-z][a-z][a-z])+$', 16, ['dfa', 'periodic', 'b26']),
    ('dfa_nested_deep', '^((a|b)(c|d)(e|f)(g|h))+$', 16, ['dfa', 'nested', 'periodic']),
    ('dfa_varloop', '^(ab|cde|fghi|jklmn)+$', (2, 12), ['dfa', 'loop', 'varlen']),
]

assert len(CORPUS) == 150
assert len({e[0] for e in CORPUS}) == 150  # unique ids
