Document: python-fte
Title: Debian python-fte Manual
Author: <insert document author here>
Abstract: This manual describes what python-fte is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-fte/python-fte.sgml.gz

Format: postscript
Files: /usr/share/doc/python-fte/python-fte.ps.gz

Format: text
Files: /usr/share/doc/python-fte/python-fte.text.gz

Format: HTML
Index: /usr/share/doc/python-fte/html/index.html
Files: /usr/share/doc/python-fte/html/*.html
